import { createAutoEdit } from "../pipeline/createAutoEdit";

async function main() {
  const result = await createAutoEdit({
    files: [
      "D:/Dropbox/02 Clients/Maly Files/Videos/Well Damn.mp4",
      "D:/Dropbox/02 Clients/Maly Files/Videos/Desert Perpetual Remix.mp4"
    ],
    targetDuration: 60,
    mode: "free",
    style: "viral",
    enableOverlays: true,
    captions: [
      {
        text: "This edit was generated by KS-Vid-Lite",
        start: 0,
        end: 4
      },
      {
        text: "Fast cuts. Clean workflow. Ready to post.",
        start: 4,
        end: 8
      },
      {
        text: "Built for creators who move fast.",
        start: 8,
        end: 12
      }
    ],
    outputPath:
      "D:/Dropbox/05 Development/KS-Vid-Lite/backend/test-assets/auto-edit-output.mp4"
  });

  console.log(JSON.stringify(result, null, 2));
}

main().catch(console.error);